version: 0.2

phases:
  install:
    commands:
    - sudo apt-add-repository ppa:brightbox/ruby-ng
    - sudo apt-get update
    - sudo apt-get install ruby2.3 ruby2.3-dev -y
    - sudo apt-get install jq -y
    - aws configure set region us-west-2
  pre_build:
    commands:
    - echo Noting to do in pre_build phase ...
  build:
    commands:
    - echo Build started on `date`
    - make
  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  files:
  - build/merged.yml
  discard-paths: yes
